base_url = "https://grand-omega.github.io"
title = "Grand Ωmega"
description = "Knowledge base and blog for Grand Ωmega"
compile_sass = true
build_search_index = true
generate_feeds = false
taxonomies = [{name = "tags", feed = false}]

[markdown.highlighting]
theme = "dracula"

[search]
include_title = true
include_description = true
include_path = true
include_content = true

[extra]
